name: run-gtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
      - name: install dependencies
        run: sudo apt install libglfw3-dev wget
      - name: get GLM
        run: wget https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip && unzip glm-0.9.9.8.zip && cp -r glm/glm src/lib/glm
      - name: get ImGui
        run: wget https://github.com/ocornut/imgui/archive/refs/tags/v1.90.1.zip && unzip v1.90.1.zip && mkdir src/lib/imgui && cp imgui-1.90.1/*.cpp src/lib/imgui && cp imgui-1.90.1/*.h src/lib/imgui && cp imgui-1.90.1/backends/*opengl3* src/lib/imgui && cp imgui-1.90.1/backends/*glfw* src/lib/imgui
      - name: setup
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make -j2
      - name: run tests
        run: build/src/tests/test